---
title: "Скрита информация и неблагоприятна селекция"
author: "Виктор Аврамов"
format:
  revealjs:
    incremental: true
    smaller: true
    scrollable: true
    css: style.css
---

## Скрита информация: Въведение

- В теорията на договора проблемът на скритата информация (наричаме това още **неблагоприятна селекция**) възниква, когато едната страна в сделка има информация, недостъпна за другата.

- Обикновено имаме следната структура: 
  - принципал сключва договор с агент, който има скрита информация.
- Търсим следното решение: Разделяне (**screening**) на различните типове агенти чрез дизайна на договора.

- Основни източници: (Akerlof, 1970), (Mirrlees, 1971), (Spence, 1972)

---

## Елементи на модела принципал-агент модел

- **Принципал**: този, който има интерес/проблем за решаване, създава дизайна на договора, има преговорна сила.
- **Агент**: има скрита информация за своя тип $\theta$.
- **Договор**: включва пакет $(x,t)$, където:
  - $x$: количество/качество на продукт или услуга.
  - $t$: плащане от агента към принципала.

---

## Предпочитания и полезност

- Печалба на принципала:
$$
\pi = t - c(x)
$$

- Полезност на агента:
$$
U(\theta) = v(x,\theta) - t
$$

- Резервна полезност (външна опция):
$$
U(0,\theta) = v(0,\theta)
$$

---

## Сравнение със случай при наличие на пълна информация

Когато типът $\theta$ е известен на принципала:

- Постига се най-доброто решение (first-best):
$$
\max_{x} [v(x,\theta)- c(x)]
$$

- Индивидуална рационалност е задължително и обвързващо условие:
$$
v(x,\theta) - t = v(0,\theta)
$$

- Резултатът е социално ефикасен

---

## Single-Crossing Property

Основно допускане за разделяне на типовете:

- По-високият тип има по-висока пределна полезност:
$$
\frac{\partial^2 v(x,\theta)}{\partial x \partial \theta}>0
$$

- По-високите типове предпочитат по-големи количества $x$.

---

## Принцип на разкриване на информацията (Revelation Principle)

Всеки механизъм може да бъде заменен с **директен механизъм за разкриване на информацията**:

- Агентът директно докладва тип $\hat{\theta}$ и получава $(x(\hat{\theta}), t(\hat{\theta}))$.
- Разкриването на информацията е равновесие на Неш.

---

## Стимули за разкриване на информацията (съчетаване на стимулите)

- Условия за равновесие на Неш при разкриване на информацията:

  - Съчетаване на стимулите (условие за участие)
$$
v(x(\theta),\theta) - t(\theta) \geq v(x(\hat{\theta}),\theta)-t(\hat{\theta}),\quad \forall \hat{\theta}\neq \theta
$$

  - Индивидуална рационалност:
$$
v(x(\theta),\theta)-t(\theta)\geq v(0,\theta)
$$

---

## Модел с два дискретни типа

- Два типа агенти: висок ($\theta_H$) и нисък ($\theta_L$), където  $\theta_H > \theta_L$

- Принципалът максимизира:
$$
\max_{(x_L,t_L),(x_H,t_H)} [\pi_L + \pi_H]
$$

- под ограниченията (условията) за участие и информация.

- **Оптимално решение**:

  - Високият тип получава информационна рента.
  - Ниският тип получава нулева рента.
  - **Ефикасност за високия тип**, неефикасност за ниския тип.

---

## Примери за скрита информация

Следват два класически примера, ясно илюстриращи основните концепции.

---

## Пример 1: Пазарът на „лимони“ (George Akerlof 1970)

- Автомобилите на пазара са два типа: добри („праскови“) и лоши („лимони“).
- Купувачите не знаят типа, продавачите знаят.
- В условие на равновесие добрите коли напускат пазара, остават само лошите.
- Това води до пазарен провал, породен от асиметричната информация (неблагоприятна селекция).

---

## Пример - продължение

- Добри коли: 
  - оценката на купувача е = \$10,000, 
  - оценката на продавача е = \$8,000.
- Лоши коли: 
  - оценката на купувача е  \$4,000, 
  - оценката на продавача е \$2,000.
- Разпределението на добри коли е = $q$, на лошите = $(1-q)$

---

## Пример - продължение

1. Продавачите решават дали да продадат колата си.
2. Купувачите формират вярвания за качеството на автомобила и определят готовността си да платят въз основа на очакваното качество.
3. Трансакцията се извършва на равновесна цена, определена от убежденията на купувачите.

---

## Пример - продължение

- Нека при пазарно равновесие желанието на купувачите да платят ($P$) се основава на очакваната стойност:
$$
P = 10,000 \times q + 4,000 \times (1-q) = 4,000 + 6,000 q
$$

- **Правило за взаимане на решение на продавачите**: 
- Продавачът на праскови: Продава, ако $P \geq 8,000$ 
- Продавачът на лимони: Продава, ако $P \geq 2000$

- Ако всички продавачи първоначално предлагат автомобили, първоначалното желание на купувача да плати може да е високо.
- Въпреки това, при равновесие, прасковите се оттеглят от пазара, ако цената е под $8000.

- **Вашата задача следващият път ще бъде да демонстрирате това!**

---

## Изводи

- **Скритата информация** води до **неблагоприятна селекция**: 
- Качествените продукти излизат от пазара. 
- Пазарът се "развива" към присъствие на най-нискокачествените продукти.
- Губи се благосъстояние, защото част от възможните трансакции не се осъществяват поради информационна асиметрия.

---

## Пример 2: Сигнализиране на пазара на труда (Michael Spence 1971)

- Производителността на работниците не е известна на фирмите: 
- **Висока производителност**: ползата е $100 000 за фирмите. 
- **Ниска производителност**: ползата е $60 000 за фирмите.
- Работниците знаят своя тип производителност.
- Образованието служи като скъп сигнал: 
- **НЕ подобрява директно производителността**. 
- Разходите за образование са по-ниски за работници с висока производителност.

---

## Пример 2: Сигнализиране на пазара на труда - продължение

1. Работниците решават дали да инвестират в образованието.
2. Работодателите формират вярвания за производителността на работниците въз основа на образователния сигнал.
3. Работодателите определят заплати на основата на тези вярвания
4. Равновесието се постига на базата на сигналите на работниците и вярванията на работодателите.

---

## Пример 2: Сигнализиране на пазара на труда - продължение


| Тип   | Продуктивност | Цена на образованието |
|-------|---------------|-----------------------|
| Висок | \$100K        | \$20K                 |
| Нисък | \$60K         | \$30K                 |

**Потенциални равновесни заплати**: 
- Ако е работникът е образован: заплата = 100 000 долара 
- Ако е работникът не е образован:: заплата = 60 000 долара

---

## Пример 2: Сигнализиране на пазара на труда - продължение


- Условие за участие на високия тип (инвестиране в образование): 
  $$
  100,000 - 20,000 \geq 60,000 \quad 
  $$ 

- Работникът от висок тип инвестира в образованието.

- Условие за участие на ниския тип (инвестиране в образование): 
$$ 
60 000 \geq 100 000 - 30 000
$$ 

- Работникът с нисък тип не инвестира в образование (ако това неравенство е удовлетворено).


---

## Условия за скрийнинг

За да постигнат ясно разделяне на типовете работници, фирмите леко коригират заплатите или изискванията:

- Да допуснем, че заплатата за образованите работници леко намали до 90 000 долара: 
- висок тип: 
$$
  90,000 - 20,000 \geq 60,000 \quad \
$$
- нисък тип: 
$$
  60,000 \geq 90,000 - 30,000 \quad 
$$
- Сега съществува ясно отделяне на равновесие при заплата 90 000 долара.

---

## Условия за скрийнинг

- **висок тип**: 
- Избира да инвестира в образование, нетната печалба = 70 000 долара
- **нисък тип **: 
- Избира да не инвестира в образование, нетната печалба = 60 000 долара
- Работодателите правилно разграничват типовете на базата на образованието.

---


## Сравнение между моделите на Akerlof и Spence

| Характеристика      | Пазар на лимони (Akerlof)  | Пазар на труда (Spence)|
|---------------------|------------------|-----------------------|
| Основен проблем     | Неблагоприятна селекция| Скрита продуктивност |
| Механизъм           | Няма сигнал      | Скъп сигнал           |
| Равновесие          | Pooling (неефикасност)| Separating (ефикасност)|
| Пазарен резултат    | Пазарна неефиканост/провал | Пазарна ефикасност |

---

## Изводи

- Скрита информация създава информационни ренти/приходи за извличане.
- Пазарът се проваля без механизми за разделяне на типовете и сигнализиране.
- Скъпите сигнали възстановяват пазарната ефикасност

